### ISSUE TITLE
TODO : Part Web

### ISSUE THREAD

**Issue by Jayllyz** [Jayllyz/TeamEase#2]
# TODO LIST :
- [x] Page d'accueil @userMeh 
- [x] Connexion & Inscription & Deco @Jayllyz 
- [x] [Back-office clients](https://github.com/Jayllyz/TeamEase/issues/13) @Jayllyz 
- [x] Mots de passe oubliés @Jayllyz 
- [x] reCAPTCHA & INSEE API @Jayllyz 
- [x] Ajout d'activité @userMeh 
- [x] Catalogue d'activité @userMeh 
- [x] Filtrage des activités @userMeh 
- [x] Page gestion du matériel @userMeh 
- [x] Back-office/dashboard activités @Jayllyz @userMeh  
- [x] Page d'activité @userMeh
- [x] Edition d'activité @userMeh
- [x] Gestion des locaux/salle @userMeh 
- [x] Page de consultation facture / devis @minatoco 
- [x] Page de consultation des réservations @minatoco 
- [x] Notation / Avis sur activité
- [x] Réservations / Paiement d'une activité ([Stripe](https://stripe.com/fr)) @Jayllyz @userMeh 
- [x] Page à propos @minatoco 
- [ ] Option multilingue (Fra & Eng)
- [ ] Responsive / Mobile / Mode dark
- [ ] Ajouter des logs
- [x] Page profil @minatoco 
- [x] planning @minatoco
