### ISSUE TITLE
TODO : Part Network / Security

### ISSUE THREAD

**Issue by Jayllyz** [Jayllyz/TeamEase#3]
# TODO LIST :
- [x] Simulation Réseau
- [x] Virtualisation Réseau
- [x] Maquette cisco
- [x] Mettre en place Sécurité VPN
- [ ] Mettre en place Sécurité AD
- [x] Mettre en place NAS
- [x] Mettre en place Sécurité Pare-Feu
- [ ] Tailscale 
- [ ] GPO
- [ ] Configurer les active directory
- [ ] mettre en place les active directory des autres 
- [ ] mettre les pc et NAS dans l'AD et configurer des utilisateurs
- [ ] déployer l'appli sur le serveur web
- [ ] Crypter les données des disques et du NAS
